/**
 * src/app/api/stripe/webhook/route.ts
 *
 * POST /api/stripe/webhook
 *
 * Stripe sends events here after payment. We handle:
 *   checkout.session.completed  → fulfill report or activate Pro
 *   customer.subscription.deleted → downgrade user to free
 *
 * Required env vars:
 *   STRIPE_SECRET_KEY
 *   STRIPE_WEBHOOK_SECRET      whsec_xxx  (from Stripe dashboard → Webhooks)
 *
 * For email delivery of the report, also set:
 *   RESEND_API_KEY             re_xxx  (free at resend.com — 3000 emails/mo)
 *   EMAIL_FROM                 info@staircode.app
 *
 * Register this webhook URL in Stripe dashboard:
 *   https://staircode.app/api/stripe/webhook
 *   Events to listen for:
 *     checkout.session.completed
 *     customer.subscription.deleted
 */

import { NextRequest, NextResponse } from 'next/server'
import Stripe                        from 'stripe'
import { trackServer }               from '@/lib/analytics-server'
import { unlockProScans }            from '@/lib/scan-usage'

async function getSupabaseAdmin() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) return null
  const { createClient } = await import('@supabase/supabase-js')
  return createClient(url, key)
}

function getStripe(): Stripe | null {
  const key = process.env.STRIPE_SECRET_KEY
  if (!key) return null
  return new Stripe(key, { apiVersion: '2024-06-20' })
}

// Reassemble report from chunked metadata
function reassembleReport(metadata: Record<string, string>): string {
  const chunks: string[] = []
  for (let i = 1; i <= 3; i++) {
    if (metadata[`reportData_${i}`]) chunks.push(metadata[`reportData_${i}`])
    else break
  }
  return chunks.join('')
}

// Send report PDF by email via Resend (resend.com — free tier: 3000/mo)
async function sendReportEmail(to: string, reportText: string, product: string) {
  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) {
    console.warn('[webhook] RESEND_API_KEY not set — skipping email delivery')
    return
  }

  const from    = process.env.EMAIL_FROM ?? 'info@staircode.app'
  const subject = product === 'report'
    ? 'Your Staircode Compliance Report'
    : 'Welcome to Staircode Pro'

  const html = product === 'report'
    ? `
      <div style="font-family:Georgia,serif;max-width:680px;margin:0 auto;padding:2rem;color:#1a2b3c">
        <div style="text-align:center;border-bottom:2px solid #1565C0;padding-bottom:1rem;margin-bottom:2rem">
          <img src="https://staircode.app/logo_dark_blue.png" alt="stAIrcode" style="height:36px;object-fit:contain;display:block;margin:0 auto;" />
          <div style="font-size:1.3rem;font-weight:600;margin-top:0.3rem">Stair Compliance Pre-Inspection Report</div>
          <div style="font-size:0.85rem;color:#666;margin-top:0.2rem">${new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        </div>
        <pre style="white-space:pre-wrap;font-family:Georgia,serif;font-size:11pt;line-height:1.7;color:#1a2b3c">${reportText}</pre>
        <div style="margin-top:3rem;border-top:1px solid #ccc;padding-top:1rem;font-size:9pt;color:#999;text-align:center">
          Generated by stAIrcode · staircode.app · © ${new Date().getFullYear()} Just Open Technologies Inc.<br>
          This report is for informational purposes only and does not constitute a certified inspection.
        </div>
      </div>
    `
    : `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:2rem;color:#1a2b3c">
        <img src="https://staircode.app/logo_dark_blue.png" alt="stAIrcode" style="height:36px;object-fit:contain;display:block;margin:0 auto 1rem;" />
        <h1 style="font-size:1.4rem;font-weight:800;margin:0 0 0.5rem">Welcome to Staircode Pro 🎉</h1>
        <p style="color:#555;line-height:1.6">Your Pro subscription is now active. You have unlimited scans, full compliance reports, and access to all supported building codes.</p>
        <a href="https://staircode.app" style="display:inline-block;margin-top:1.5rem;padding:0.85rem 2rem;background:#1565C0;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Open Staircode →</a>
        <p style="margin-top:2rem;font-size:0.8rem;color:#999">Manage your subscription at staircode.app/settings · Cancel anytime.</p>
      </div>
    `

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify({ from, to, subject, html }),
    })
    if (!res.ok) {
      const err = await res.text()
      console.error('[webhook] Resend error:', err)
    } else {
      console.log('[webhook] Email sent to', to)
    }
  } catch (err) {
    console.error('[webhook] Email send failed:', err)
  }
}

// ── Webhook handler ────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  const stripe = getStripe()
  if (!stripe) {
    return NextResponse.json({ error: 'Stripe not configured' }, { status: 503 })
  }

  const sig    = req.headers.get('stripe-signature') ?? ''
  const secret = process.env.STRIPE_WEBHOOK_SECRET
  const body   = await req.text()

  if (!secret) {
    console.warn('[webhook] STRIPE_WEBHOOK_SECRET not set — skipping signature verification')
    return NextResponse.json({ error: 'Webhook secret not configured' }, { status: 503 })
  }

  // Verify Stripe signature
  let event: Stripe.Event
  try {
    event = stripe.webhooks.constructEvent(body, sig, secret)
  } catch (err: any) {
    console.error('[webhook] Signature verification failed:', err.message)
    return NextResponse.json({ error: 'Invalid signature' }, { status: 400 })
  }

  // ── Handle events ──────────────────────────────────────────────────────────
  try {
    switch (event.type) {

      case 'checkout.session.completed': {
        const session  = event.data.object as Stripe.Checkout.Session
        const meta     = session.metadata ?? {}
        const product  = meta.product
        const email    = meta.userEmail || session.customer_email || ''
        const report   = reassembleReport(meta)

        console.log(`[webhook] checkout.session.completed — product: ${product}, email: ${email}`)

        // Track purchase server-side — source of truth (browser may have closed)
        if (email) {
          await trackServer(email, 'purchase_completed_server', {
            product,
            stripe_session: session.id,
            amount_cents:   product === 'report' ? 299 : 3899,
          })
        }

        const sb = await getSupabaseAdmin()

        if (product === 'report' && email) {
          // 1. Save purchase record to Supabase
          if (sb) {
            await sb.from('report_purchases').insert({
              email,
              product:        'report',
              stripe_session: session.id,
              amount_cents:   299,
              used:           false,
              created_at:     new Date().toISOString(),
            }).then(({ error }) => {
              if (error) console.error('[webhook] Failed to save purchase:', error)
            })
          }

          // 2. Email the report immediately after payment
          // (The full report text is chunked in metadata)
          if (report) await sendReportEmail(email, report, 'report')
          else {
            // Report text wasn't in metadata (too long) — send a notification
            // The user can view/export the report from inside the app
            await sendReportEmail(email, '[Report generated in-app — please open Staircode to view and export your report.]', 'report')
          }
        }

        if (product === 'pro' && email) {
          // Upgrade user to Pro in Supabase
          if (sb) {
            await sb.from('profiles')
              .upsert({ email, membership: 'pro', updated_at: new Date().toISOString() }, { onConflict: 'email' })
              .then(({ error }) => { if (error) console.error('[webhook] Failed to update membership:', error) })
          }
          // Unlock unlimited scans in scan_usage table
          await unlockProScans(email)
          await sendReportEmail(email, '', 'pro')
        }

        break
      }

      case 'customer.subscription.deleted': {
        const sub   = event.data.object as Stripe.Subscription
        const email = sub.metadata?.userEmail
        if (email) {
          console.log(`[webhook] Subscription cancelled for ${email}`)
          // Downgrade in Supabase:
          // await supabase.from('profiles').update({ membership: 'free' }).eq('email', email)
        }
        break
      }

      default:
        // Unhandled event type — ignore silently
        break
    }
  } catch (err) {
    console.error('[webhook] Handler error:', err)
    return NextResponse.json({ error: 'Handler failed' }, { status: 500 })
  }

  return NextResponse.json({ received: true })
}
