/**
 * src/app/api/stripe/webhook/route.ts
 *
 * POST /api/stripe/webhook
 *
 * Handles Stripe events:
 *   checkout.session.completed       → activate subscription, send welcome email
 *   customer.subscription.created    → mark user active in Supabase
 *   customer.subscription.updated    → sync status changes
 *   customer.subscription.deleted    → downgrade user to free tier
 *
 * All products funnel into the single $38.99/month subscription.
 * No per-report payments exist.
 *
 * Required env vars:
 *   STRIPE_SECRET_KEY
 *   STRIPE_WEBHOOK_SECRET      whsec_xxx  (from Stripe dashboard → Webhooks)
 *   RESEND_API_KEY             re_xxx
 *   EMAIL_FROM                 info@staircode.app
 *
 * Register this webhook URL:
 *   https://staircode.app/api/stripe/webhook
 *   Events:
 *     checkout.session.completed
 *     customer.subscription.created
 *     customer.subscription.updated
 *     customer.subscription.deleted
 */

import { NextRequest, NextResponse } from 'next/server'
import Stripe                        from 'stripe'
import { trackServer }               from '@/lib/analytics-server'
import { unlockProScans }            from '@/lib/scan-usage'

async function getSupabaseAdmin() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) return null
  const { createClient } = await import('@supabase/supabase-js')
  return createClient(url, key)
}

function getStripe(): Stripe | null {
  const key = process.env.STRIPE_SECRET_KEY
  if (!key) return null
  return new Stripe(key, { apiVersion: '2024-06-20' })
}

// Reassemble report from chunked metadata
function reassembleReport(metadata: Record<string, string>): string {
  const chunks: string[] = []
  for (let i = 1; i <= 3; i++) {
    if (metadata[`reportData_${i}`]) chunks.push(metadata[`reportData_${i}`])
    else break
  }
  return chunks.join('')
}

// Send report PDF by email via Resend (resend.com — free tier: 3000/mo)
async function sendReportEmail(to: string, reportText: string, product: string) {
  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) {
    console.warn('[webhook] RESEND_API_KEY not set — skipping email delivery')
    return
  }

  const from    = process.env.EMAIL_FROM ?? 'info@staircode.app'
  const subject = product === 'subscription' || product === 'pro'
    ? 'Welcome to stAIrcode — Subscription Active'
    : 'Your stAIrcode Compliance Report'

  const html = product === 'report'
    ? `
      <div style="font-family:Georgia,serif;max-width:680px;margin:0 auto;padding:2rem;color:#1a2b3c">
        <div style="text-align:center;border-bottom:2px solid #1565C0;padding-bottom:1rem;margin-bottom:2rem">
          <img src="https://staircode.app/logo_dark_blue.png" alt="stAIrcode" style="height:36px;object-fit:contain;display:block;margin:0 auto;" />
          <div style="font-size:1.3rem;font-weight:600;margin-top:0.3rem">Stair Compliance Pre-Inspection Report</div>
          <div style="font-size:0.85rem;color:#666;margin-top:0.2rem">${new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        </div>
        <pre style="white-space:pre-wrap;font-family:Georgia,serif;font-size:11pt;line-height:1.7;color:#1a2b3c">${reportText}</pre>
        <div style="margin-top:3rem;border-top:1px solid #ccc;padding-top:1rem;font-size:9pt;color:#999;text-align:center">
          Generated by stAIrcode · staircode.app · © ${new Date().getFullYear()} Just Open Technologies Inc.<br>
          This report is for informational purposes only and does not constitute a certified inspection.
        </div>
      </div>
    `
    : `
      <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:2rem;color:#1a2b3c">
        <img src="https://staircode.app/logo_dark_blue.png" alt="stAIrcode" style="height:36px;object-fit:contain;display:block;margin:0 auto 1rem;" />
        <h1 style="font-size:1.4rem;font-weight:800;margin:0 0 0.5rem">Welcome to stAIrcode</h1>
        <p style="color:#555;line-height:1.6">Your subscription is active at $38.99/month. You now have full access to the complete building inspection platform — all inspection phases, AI vision scans, photo documentation, and comprehensive compliance reports.</p>
        <a href="https://staircode.app" style="display:inline-block;margin-top:1.5rem;padding:0.85rem 2rem;background:#0A1C2E;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Start Your Inspection →</a>
        <p style="margin-top:2rem;font-size:0.8rem;color:#999">Manage or cancel at staircode.app/settings · Cancel anytime.</p>
      </div>
    `

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify({ from, to, subject, html }),
    })
    if (!res.ok) {
      const err = await res.text()
      console.error('[webhook] Resend error:', err)
    } else {
      console.log('[webhook] Email sent to', to)
    }
  } catch (err) {
    console.error('[webhook] Email send failed:', err)
  }
}

// ── Webhook handler ────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  const stripe = getStripe()
  if (!stripe) {
    return NextResponse.json({ error: 'Stripe not configured' }, { status: 503 })
  }

  const sig    = req.headers.get('stripe-signature') ?? ''
  const secret = process.env.STRIPE_WEBHOOK_SECRET
  const body   = await req.text()

  if (!secret) {
    console.warn('[webhook] STRIPE_WEBHOOK_SECRET not set — skipping signature verification')
    return NextResponse.json({ error: 'Webhook secret not configured' }, { status: 503 })
  }

  // Verify Stripe signature
  let event: Stripe.Event
  try {
    event = stripe.webhooks.constructEvent(body, sig, secret)
  } catch (err: any) {
    console.error('[webhook] Signature verification failed:', err.message)
    return NextResponse.json({ error: 'Invalid signature' }, { status: 400 })
  }

  // ── Handle events ──────────────────────────────────────────────────────────
  try {
    switch (event.type) {

      case 'checkout.session.completed': {
        const session  = event.data.object as Stripe.Checkout.Session
        const meta     = session.metadata ?? {}
        const product  = meta.product
        const email    = meta.userEmail || session.customer_email || ''
        const report   = reassembleReport(meta)

        console.log(`[webhook] checkout.session.completed — product: ${product}, email: ${email}`)

        // Track purchase server-side — source of truth (browser may have closed)
        if (email) {
          await trackServer(email, 'purchase_completed_server', {
            product,
            stripe_session: session.id,
            amount_cents:   3899,
          })
        }

        const sb = await getSupabaseAdmin()

        // All products activate the subscription
        if (email) {
          if (sb) {
            // Activate subscription in profiles table
            await sb.from('profiles').upsert({
              email,
              membership:             'subscription',
              subscription_active:    true,
              subscription_start:     new Date().toISOString(),
              stripe_customer_id:     session.customer as string ?? null,
              stripe_subscription_id: session.subscription as string ?? null,
              updated_at:             new Date().toISOString(),
            }, { onConflict: 'email' }).then(({ error }) => {
              if (error) console.error('[webhook] Failed to activate subscription:', error)
              else console.log(`[webhook] Subscription activated for ${email}`)
            })
          }
          // Unlock unlimited scans
          await unlockProScans(email)
          // Stop the trial email sequence — user has converted
          if (sb) {
            await sb.from('trials').update({ subscribed: true }).eq('email', email.toLowerCase())
              .then(({ error }) => { if (error) console.error('[webhook] trial mark-subscribed failed:', error.message) })
          }
          // Send welcome email
          await sendReportEmail(email, '', 'subscription')
        }

        break
      }

      case 'customer.subscription.created':
      case 'customer.subscription.updated': {
        const sub    = event.data.object as Stripe.Subscription
        const email  = sub.metadata?.userEmail
        const active = (sub.status === 'active' || sub.status === 'trialing')
        if (email) {
          const sb = await getSupabaseAdmin()
          if (sb) {
            await sb.from('profiles').upsert({
              email,
              membership:          active ? 'subscription' : 'free',
              subscription_active: active,
              stripe_subscription_id: sub.id,
              updated_at:          new Date().toISOString(),
            }, { onConflict: 'email' }).then(({ error }) => {
              if (error) console.error('[webhook] Failed to sync subscription:', error)
              else console.log(`[webhook] Subscription ${sub.status} for ${email}`)
            })
          }
          if (active) await unlockProScans(email)
        }
        break
      }

      case 'customer.subscription.deleted': {
        const sub   = event.data.object as Stripe.Subscription
        const email = sub.metadata?.userEmail
        if (email) {
          console.log(`[webhook] Subscription cancelled for ${email}`)
          const sb = await getSupabaseAdmin()
          if (sb) {
            await sb.from('profiles').update({
              membership:          'free',
              subscription_active: false,
              updated_at:          new Date().toISOString(),
            }).eq('email', email).then(({ error }) => {
              if (error) console.error('[webhook] Failed to downgrade:', error)
            })
          }
        }
        break
      }

      default:
        // Unhandled event type — ignore silently
        break
    }
  } catch (err) {
    console.error('[webhook] Handler error:', err)
    return NextResponse.json({ error: 'Handler failed' }, { status: 500 })
  }

  return NextResponse.json({ received: true })
}
