'use client'
/**
 * ReportScreen.tsx — ARAI_10
 *
 * Three purchase options:
 *   $11.99  — Full professional report (one-time, this inspection)
 *   $38.99/mo — Pro (unlimited scans + reports, AR mode)
 *   Enterprise — Contact Sales
 *
 * Plus: Find Architect (free), Retake, Start Over.
 *
 * The $11.99 report is generated by Claude via /api/vision with a text-only
 * prompt (no image needed at this stage) and includes:
 *   - Stair description
 *   - Compliance analysis per field
 *   - Applicable building code standards
 *   - Most likely occupancy type based on location + measurements
 *   - Relevant bylaw notes
 *   - Pre-inspection summary for a building inspector
 */

import { useState, useEffect, useCallback, useRef } from 'react'
import { Analytics } from '@/lib/analytics'
import posthog from 'posthog-js'
import { BetaLogo } from '@/app/components/Logo'
import { getProfile } from '@/lib/profiles'
import type { UserRole } from './AuthScreen'
import type { StairMeasurements } from './MeasureWalk'

// ── Design tokens — static (non-profile-specific) ────────────────────────────
const ORANGE = '#F29337'
const GOLD   = '#F29337'  // brand orange
// Profile-driven tokens are accessed via profile.bg, profile.accent, etc.

interface FieldResult {
  label:       string
  icon:        string
  value:       number | null
  min?:        number
  max?:        number
  pass:        boolean | null
  clearAbove?: boolean
}

interface Props {
  measurements: StairMeasurements
  fields:       FieldResult[]
  codeLabel:    string
  codeRef:      string
  location:     string
  userLatLng:   { lat: number; lng: number } | null
  isOntario:    boolean
  userRole?:    UserRole
  onRetake:     () => void
  onStartOver:  () => void
}

type Sheet = 'hidden' | 'plans' | 'purchase-report' | 'report-ready' | 'free-confirm'

// ── Generate the full professional report via Claude ──────────────────────────
async function generateFullReport(
  measurements: StairMeasurements,
  fields: FieldResult[],
  codeLabel: string,
  codeRef: string,
  location: string,
  isOntario: boolean
): Promise<string | null> {

  const measurementSummary = fields.map(f => {
    const val = f.clearAbove ? 'CLEAR/OPEN' : f.value != null ? `${Math.round(f.value)}mm` : 'Not measured'
    const range = f.min != null && f.max != null ? `${f.min}–${f.max}mm` : f.min != null ? `≥${f.min}mm` : f.max != null ? `≤${f.max}mm` : 'N/A'
    const status = f.pass === true ? 'PASS' : f.pass === false ? 'FAIL' : 'N/A'
    return `${f.label}: ${val} (required: ${range}) — ${status}`
  }).join('\n')

  const failedItems = fields.filter(f => f.pass === false)
    .map(f => `${f.label}: measured ${f.value}mm, required ${f.min != null && f.max != null ? `${f.min}–${f.max}mm` : f.min != null ? `≥${f.min}mm` : `≤${f.max}mm`}`)
    .join('\n')

  const prompt = `You are a professional building code compliance consultant producing a formal pre-inspection stair assessment report. Write clearly, precisely, and professionally — like a licensed building inspector's report.

INSPECTION DATA:
Location: ${location || 'Unknown'}
Jurisdiction: ${codeLabel} (${codeRef})
${isOntario ? 'Province: Ontario, Canada' : ''}
Measurement confidence: ${Math.round(measurements.confidence * 100)}%

MEASUREMENTS:
${measurementSummary}

${failedItems ? `FAILED ITEMS:\n${failedItems}` : 'All measured items passed.'}

Riser count: ${measurements.riserCount ?? 'Unknown'}
Handrail: ${measurements.handrailBothSides ? 'Both sides' : measurements.handrailOneSide ? 'One side' : 'Unknown'}
Nosing: ${(measurements as any).nosing === 'none' ? 'No nosing detected' : (measurements as any).nosing ? `~${(measurements as any).nosing}mm projection` : 'Not assessed'}
Headroom: ${measurements.headroom === 'clear' ? 'Open/clear above' : measurements.headroom ? `~${measurements.headroom}mm` : 'Not assessed'}

Write a professional report with the following sections. Use plain text, no markdown symbols, no asterisks. Use numbered sections with clear headings.

1. STAIR DESCRIPTION
Describe the staircase based on the measurements — approximate type (straight residential, commercial, etc.), estimated number of risers, overall dimensions, and general character.

2. COMPLIANCE ANALYSIS
For each measured dimension, explain what was found versus what is required under ${codeLabel}. Be specific about the actual values and the code requirement. State clearly whether each item passes or fails. For failed items, state the exact deficiency in mm.

3. APPLICABLE BUILDING CODE STANDARDS
List the specific sections of ${codeLabel} (${codeRef}) that apply to this staircase, with a plain-language explanation of what each section requires.

4. PROBABLE OCCUPANCY CLASSIFICATION
Based on the location (${location}), stair dimensions, and measurement profile, state the most likely occupancy type (e.g., Part 9 residential dwelling, Part 3 assembly, commercial/IBC Group B, etc.) and explain why. Note how occupancy affects the applicable code requirements.

5. BYLAW AND LOCAL AMENDMENT NOTES
Note any relevant local amendments or bylaws likely applicable in ${location}. If the jurisdiction is Ontario, note relevant OBC 2024 amendments. Include any known variance procedures or exemptions that may apply.

6. RISK ASSESSMENT FOR INSPECTOR
Summarise the key compliance risks in order of severity. Flag any items that would typically trigger a stop-work order or require immediate remediation versus items that may be subject to discretion or field measurement verification. Provide a concise recommendation on whether a formal inspection is advisable before occupancy.

7. DISCLAIMER
Include a standard disclaimer that this is a pre-inspection AI analysis, not a certified inspection, and that a licensed building official's determination takes precedence.

Write the full report now.`

  try {
    const ctrl    = new AbortController()
    const timeout = setTimeout(() => ctrl.abort(), 45_000)
    const r = await fetch('/api/vision', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      // Send a blank 1x1 image — we only need the text response here
      body: JSON.stringify({
        imageB64: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEBAAA/APtKKAP/2Q==',
        prompt,
      }),
      signal: ctrl.signal,
    })
    clearTimeout(timeout)
    if (!r.ok) return null
    const d = await r.json()
    return d.text ?? null
  } catch { return null }
}

// ── Component ──────────────────────────────────────────────────────────────────
export default function ReportScreen({ measurements, fields, codeLabel, codeRef, location, userLatLng, isOntario, userRole, onRetake, onStartOver }: Props) {
  const profile = getProfile(userRole)

  // Token aliases for convenience (profile-driven)
  const BG     = profile.bg
  const BG2    = profile.bg2
  const BG3    = profile.bg3
  const TEXT   = profile.text
  const TEXT2  = profile.text2
  const TEXT3  = profile.text3
  const PASS   = profile.pass
  const FAIL   = profile.fail
  const WARN   = profile.warn
  const BLUE   = profile.accent
  const BORDER = `1px solid ${profile.bg3}`
  const [sheet,        setSheet]        = useState<Sheet>('hidden')
  const [reportText,   setReportText]   = useState<string | null>(null)
  const [generating,   setGenerating]   = useState(false)
  const [genError,     setGenError]     = useState<string | null>(null)
  const reportRef = useRef<HTMLDivElement>(null)
  const [proLoading,  setProLoading]  = useState(false)
  const [creditId,    setCreditId]    = useState<string | undefined>(undefined)
  const [emailSent,    setEmailSent]    = useState(false)
  const [emailSending, setEmailSending] = useState(false)
  const [emailInput,   setEmailInput]   = useState('')      // captures email if user skipped auth
  const [showEmailPrompt, setShowEmailPrompt] = useState(false)

  // ── PostHog experiment: 'print-report' ────────────────────────────────────
  // Tracks sign-in → report generation conversion rate.
  // 'test' variant = more prominent report CTA to see if it lifts generation rate.
  // 'control' = default behaviour (current UI unchanged)
  const [reportFlag, setReportFlag] = useState<string | null>(null)
  useEffect(() => {
    // Evaluate after PostHog initialises (slight delay to ensure loaded)
    const timer = setTimeout(() => {
      const flag = posthog.getFeatureFlag('print-report')
      const variant = typeof flag === 'string' ? flag : (flag ? 'test' : 'control')
      setReportFlag(variant ?? 'control')
      // Track experiment exposure so PostHog can calculate conversion
      posthog.capture('$experiment_started', {
        experiment_name: 'print-report',
        variant,
      })
    }, 500)
    return () => clearTimeout(timer)
  }, []) // eslint-disable-line

  const isTestVariant = reportFlag === 'test'

  const measured = fields.filter(f => f.value != null || f.clearAbove)
  const failed   = measured.filter(f => f.pass === false)
  const passed   = measured.filter(f => f.pass === true || f.clearAbove)
  const passRate = measured.length > 0 ? passed.length / measured.length : 0

  type Verdict = 'none' | 'likely' | 'possibly' | 'issues_likely' | 'probably_not' | 'fail'
  function getVerdict(): Verdict {
    if (measured.length === 0) return 'none'
    if (failed.length > 0) {
      if (passRate < 0.6) return 'probably_not'
      if (passRate < 0.8) return 'issues_likely'
      return 'fail'
    }
    if (measured.length < 3 || measurements.confidence < 0.45) return 'possibly'
    if (passRate >= 0.9 && measured.length >= 4) return 'likely'
    return 'possibly'
  }
  const verdict = getVerdict()

  const fmtMm = (v: number | null, f?: FieldResult) =>
    f?.clearAbove ? 'CLEAR' : v == null ? '—' : `${Math.round(v)}mm`

  const fmtRange = (f: FieldResult) => {
    if (f.min != null && f.max != null) return `${f.min}–${f.max}`
    if (f.min != null) return `≥${f.min}`
    if (f.max != null) return `≤${f.max}`
    return '—'
  }

  const openArchMap = useCallback(() => {
    Analytics.findInspectorClicked()
    const q = encodeURIComponent('stair architect building inspector near me')
    window.open(userLatLng
      ? `https://www.google.com/maps/search/${q}/@${userLatLng.lat},${userLatLng.lng},13z`
      : `https://www.google.com/maps/search/${q}`, '_blank')
  }, [userLatLng])

  // ── Report: generate via dedicated API + email immediately ─────────────────
  async function handlePurchaseAndGenerate() {
    // Check if we have a real email — beta skip users have 'beta@staircode.app'
    const storedEmail = (() => { try { const u = localStorage.getItem('sc_user'); return u ? JSON.parse(u).email : '' } catch { return '' } })()
    const isBetaEmail = !storedEmail || storedEmail === 'beta@staircode.app' || !storedEmail.includes('@')

    // If no real email, show prompt before generating
    if (isBetaEmail && !emailInput) {
      setShowEmailPrompt(true)
      return
    }

    setGenerating(true)
    setGenError(null)
    setSheet('purchase-report')

    const userEmail = emailInput || storedEmail

    // Save the entered email to localStorage so it persists
    if (emailInput) {
      try {
        const u = JSON.parse(localStorage.getItem('sc_user') || '{}')
        u.email = emailInput
        localStorage.setItem('sc_user', JSON.stringify(u))
      } catch {}
    }

    try {
      // Single call to /api/report/generate — generates + emails in one request
      // max_tokens reduced to 1500 for speed; maxDuration=60 on the server
      const res = await fetch('/api/report/generate', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email:     userEmail,
          fields,
          codeLabel,
          codeRef,
          location,
          isOntario,
          surveyUrl: process.env.NEXT_PUBLIC_SURVEY_URL || 'https://tally.so/r/1AMRbW',
        }),
      })

      const data = await res.json()

      if (!res.ok || !data.ok) {
        setGenerating(false)
        setGenError('Could not generate report — please try again. If the issue persists contact info@staircode.app.')
        return
      }

      // Show the report inline AND it has been emailed
      setReportText(data.reportText ?? '')
      setEmailSent(data.emailed ?? false)
      setGenerating(false)
      setSheet('report-ready')

    } catch (err) {
      console.error('[report] Generation error:', err)
      setGenerating(false)
      setGenError('Connection timed out. Please check your internet and try again.')
    }
  }

  async function printReport() {
    Analytics.exportClicked('print')
    Analytics.betaReportGenerated({ verdict, failCount: failed.length, passCount: passed.length, codeLabel, emailed: emailSent })
    // Track experiment conversion — this is the goal event PostHog measures
    posthog.capture('report_generated_experiment', {
      experiment_name: 'print-report',
      variant:         reportFlag ?? 'control',
      verdict,
    })

    // Email the report to the user (fire-and-forget alongside print)
    if (reportText && !emailSent) {
      const userEmail = (() => { try { const u = localStorage.getItem('sc_user'); return u ? JSON.parse(u).email : '' } catch { return '' } })()
      if (userEmail) {
        setEmailSending(true)
        fetch('/api/report/email', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify({ email: userEmail, reportText, creditId, codeLabel, location }),
        }).then(r => r.json()).then(d => {
          if (d.ok) setEmailSent(true)
        }).catch(() => {}).finally(() => setEmailSending(false))
      }
    }

    setTimeout(() => window.print(), 200)
  }

  // ── $38.99/mo Pro: redirect to Stripe subscription checkout ──────────────────
  async function handleProCheckout() {
    setProLoading(true)
    try {
      const userEmail = (() => { try { const u = localStorage.getItem('sc_user'); return u ? JSON.parse(u).email : '' } catch { return '' } })()
      const res = await fetch('/api/stripe/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ product: 'pro', userEmail }),
      })
      const data = await res.json()
      if (data.url) {
        window.location.href = data.url
      } else {
        // Stripe not configured — open the Pro info page instead
        window.open('https://staircode.app/pro', '_blank')
        setProLoading(false)
      }
    } catch {
      window.open('https://staircode.app/pro', '_blank')
      setProLoading(false)
    }
  }

  function printFree() {
    setSheet('hidden')
    setTimeout(() => window.print(), 250)
  }

  const confColor = measurements.confidence > 0.6 ? PASS : measurements.confidence > 0.4 ? WARN : FAIL
  const confLabel = measurements.confidence > 0.6 ? 'HIGH' : measurements.confidence > 0.4 ? 'MEDIUM' : 'LOW'
  const verdictColor  = verdict === 'likely' ? PASS : verdict === 'possibly' ? WARN : verdict === 'none' ? TEXT3 : FAIL
  const verdictBg     = verdict === 'likely' ? 'rgba(61,184,138,0.12)' : verdict === 'possibly' ? 'rgba(242,147,55,0.10)' : verdict === 'none' ? 'rgba(147,186,212,0.06)' : 'rgba(232,85,85,0.12)'
  const verdictBorder = verdict === 'likely' ? 'rgba(61,184,138,0.35)' : verdict === 'possibly' ? 'rgba(242,147,55,0.35)' : verdict === 'none' ? 'rgba(147,186,212,0.15)' : 'rgba(232,85,85,0.35)'
  const verdictLabel  = {
    none:          'No Measurements Captured',
    likely:        profile.copy.verdictLikely,
    possibly:      profile.copy.verdictPossibly,
    issues_likely: false /* professional role removed */ ? 'Issues Likely' : 'A Few Things to Check',
    probably_not:  false /* professional role removed */ ? 'Probably Non-Compliant' : 'Some Issues Found',
    fail:          profile.copy.verdictFail,
  }[verdict]
  const verdictChip = {
    none:          { label: '—',           bg: 'transparent',                   color: profile.text3 },
    likely:        { label: '✓ PASS',      bg: 'rgba(39,169,107,0.15)',         color: '#27A96B' },
    possibly:      { label: '⚠ REVIEW',   bg: 'rgba(242,147,55,0.15)',         color: '#F29337' },
    issues_likely: { label: '⚠ REVIEW',   bg: 'rgba(242,147,55,0.15)',         color: '#F29337' },
    probably_not:  { label: '✗ FAIL',     bg: 'rgba(232,69,69,0.15)',          color: '#E84545' },
    fail:          { label: '✗ FAIL',     bg: 'rgba(232,69,69,0.15)',          color: '#E84545' },
  }[verdict] ?? { label: '—', bg: 'transparent', color: profile.text3 }

  // ── Print styles injected into head ───────────────────────────────────────
  const printStyles = `
    @media print {
      body * { visibility: hidden !important; }
      #full-report-print, #full-report-print * { visibility: visible !important; }
      #full-report-print {
        position: absolute !important; left: 0 !important; top: 0 !important;
        width: 100% !important; background: white !important; color: black !important;
        padding: 2rem !important; font-family: Georgia, serif !important;
        font-size: 11pt !important; line-height: 1.7 !important;
      }
    }
  `

  // Derive userEmail once for the whole render
  const userEmail = (() => { try { const u = localStorage.getItem('sc_user'); return u ? JSON.parse(u).email : '' } catch { return '' } })()

  return (
    <div style={{ minHeight: '100dvh', background: profile.bg, color: profile.text, display: 'flex', flexDirection: 'column', maxWidth: 430, margin: '0 auto', fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif", position: 'relative' }}>
      <style>{printStyles}</style>

      {/* Hidden print-ready full report */}
      {reportText && (
        <div id="full-report-print" style={{ display: 'none' }}>
          <div style={{ textAlign: 'center', marginBottom: '2rem', borderBottom: '2px solid #333', paddingBottom: '1rem' }}>
            <img src='/logo_orange_transparent.png' alt='stAIrcode' style={{ height: 36, objectFit: 'contain' }} />
            <div style={{ fontSize: '1.1rem', fontWeight: 600, marginTop: '0.3rem' }}>Stair Compliance Pre-Inspection Report</div>
            <div style={{ fontSize: '0.85rem', color: '#555', marginTop: '0.3rem' }}>
              {codeLabel} · {location} · {new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
          </div>
          <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'Georgia, serif', fontSize: '11pt', lineHeight: 1.7, color: '#000' }}>
            {reportText}
          </pre>
          <div style={{ marginTop: '3rem', borderTop: '1px solid #ccc', paddingTop: '1rem', fontSize: '9pt', color: '#777', textAlign: 'center' }}>
            Generated by stAIrcode · staircode.app · © {new Date().getFullYear()} Just Open Technologies Inc.
          </div>
        </div>
      )}

      {/* ── PRINT HEADER (screen-hidden) ── */}
      <div className="print-header" style={{ padding: '1rem 1.25rem 0.5rem' }}>
        <img src='/logo_orange_transparent.png' alt='stAIrcode' style={{ height: 28, objectFit: 'contain' }} />
        <div style={{ fontSize: '0.65rem', color: profile.text2 }}>
          {codeLabel} · {codeRef} · {location} · {new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}
        </div>
      </div>

      {/* ── TOP BAR ── */}
      <div style={{ padding: '0.75rem 1.25rem 0', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <BetaLogo size="xs" onDark />
        <div style={{ fontSize: '0.65rem', fontFamily: 'monospace', color: profile.text3 }}>{codeLabel} · {location || 'Unknown'}</div>
      </div>

      {/* ── SCROLLABLE BODY ── */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '0.75rem 1.25rem', paddingBottom: sheet !== 'hidden' ? '1rem' : '8rem' }}>

        {/* Verdict */}
        <div style={{ borderRadius: 16, padding: '1rem 1.1rem', marginBottom: '0.75rem', background: verdictBg, border: `1.5px solid ${verdictBorder}`, display: 'flex', alignItems: 'center', gap: '0.9rem' }}>
          <div style={{ display:'inline-flex', alignItems:'center', background:verdictChip.bg, border:`1.5px solid ${verdictChip.color}`, color:verdictChip.color, fontFamily:'monospace', fontSize:'0.72rem', fontWeight:800, letterSpacing:'0.1em', padding:'0.35rem 0.85rem', borderRadius:999, flexShrink:0 }}>
          {verdictChip.label}
        </div>
          <div>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: verdictColor, lineHeight: 1.2 }}>{verdictLabel}</div>
            <div style={{ fontSize: '0.7rem', color: profile.text2, marginTop: '0.2rem', fontFamily: 'monospace' }}>
              {passed.length} passed · {failed.length} failed · {fields.length - measured.length} not measured
            </div>
            {verdict === 'possibly' && measured.length < 3 && (
              <div style={{ color: profile.warn, fontSize: '0.7rem', marginTop: '0.2rem' }}>Only {measured.length} of {fields.length} measurements captured</div>
            )}
          </div>
        </div>

        {/* Meta badges */}
        <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap', marginBottom: '0.75rem' }}>
          {[
            { label: confLabel + ' CONFIDENCE', color: confColor, bg: confColor + '22' },
            { label: codeLabel, color: profile.accent, bg: 'rgba(65,124,164,0.12)' },
            ...(measurements.calibrated ? [{ label: '📏 CALIBRATED', color: ORANGE, bg: 'rgba(242,147,55,0.15)' }] : []),
          ].map(({ label, color, bg }) => (
            <div key={label} style={{ padding: '0.25rem 0.7rem', borderRadius: 20, background: bg, border: `1px solid ${color}44`, fontSize: '0.6rem', fontFamily: 'monospace', letterSpacing: '0.07em', color, fontWeight: 700 }}>
              {label}
            </div>
          ))}
        </div>

        {/* Measurement rows */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', marginBottom: '0.75rem' }}>
          {fields.map(f => {
            const rowBg    = f.pass === true ? 'rgba(61,184,138,0.06)' : f.pass === false ? 'rgba(232,85,85,0.07)' : BG2
            const rowBdr   = f.pass === true ? 'rgba(61,184,138,0.25)' : f.pass === false ? 'rgba(232,85,85,0.3)' : profile.bg3
            const passCol  = f.pass === true ? PASS : f.pass === false ? FAIL : TEXT3
            const passIcon = f.pass === true ? '✓ OK' : f.pass === false ? '✗ FAIL' : f.value != null ? '?' : '—'
            return (
              <div key={f.label} style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', padding: '0.65rem 0.85rem', borderRadius: 12, background: rowBg, border: `1px solid ${rowBdr}` }}>
                <span style={{ fontSize: '0.9rem', width: 20, textAlign: 'center', flexShrink: 0 }}>{f.icon}</span>
                <span style={{ flex: 1, fontSize: '0.8rem', color: profile.text, fontWeight: 500 }}>{f.label}</span>
                <span style={{ fontFamily: 'monospace', fontSize: '0.88rem', fontWeight: 700, color: f.value != null ? TEXT : TEXT3 }}>{fmtMm(f.value, f)}</span>
                <span style={{ fontSize: '0.6rem', fontFamily: 'monospace', color: profile.text3, width: 62, textAlign: 'right' }}>{fmtRange(f)}</span>
                <span style={{ fontSize: '0.68rem', fontWeight: 700, width: 46, textAlign: 'right', color: passCol, flexShrink: 0, fontFamily: 'monospace' }}>{passIcon}</span>
              </div>
            )
          })}
        </div>

        {/* Failed detail */}
        {failed.length > 0 && (
          <div style={{ background: 'rgba(232,85,85,0.08)', border: `1px solid rgba(232,85,85,0.25)`, borderLeft: `3px solid ${FAIL}`, borderRadius: 12, padding: '0.75rem 0.9rem', marginBottom: '0.75rem' }}>
            <div style={{ fontSize: '0.6rem', letterSpacing: '0.12em', color: profile.fail, marginBottom: '0.5rem', fontFamily: 'monospace', fontWeight: 700 }}>ITEMS REQUIRING ATTENTION</div>
            {failed.map(f => (
              <div key={f.label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: profile.text, padding: '0.25rem 0', borderBottom: `1px solid rgba(147,186,212,0.07)` }}>
                <span>{f.label}</span>
                <span style={{ color: profile.fail, fontFamily: 'monospace', fontWeight: 600 }}>{fmtMm(f.value, f)} · need {fmtRange(f)}</span>
              </div>
            ))}
          </div>
        )}

        {/* Disclaimer */}
        <div style={{ background: 'rgba(242,147,55,0.08)', border: `1px solid rgba(242,147,55,0.2)`, borderLeft: `3px solid ${WARN}`, borderRadius: 12, padding: '0.7rem 0.9rem', fontSize: '0.65rem', color: profile.text2, lineHeight: 1.7, marginBottom: '1rem' }}>
          <strong style={{ color: profile.warn }}>Pre-Analysis Only.</strong>{' '}
          Accuracy ±9.5–25mm. This report does not substitute for inspection by a licensed architect or building inspector.
          Always verify against {codeLabel} with your local authority having jurisdiction.
        </div>

        {/* Purchase report teaser */}
        <div style={{ background: `linear-gradient(135deg, rgba(242,147,55,0.1), rgba(242,147,55,0.04))`, border: `1.5px solid rgba(242,147,55,0.35)`, borderRadius: 16, padding: '1rem 1.1rem', marginBottom: '0.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.6rem' }}>
            <span style={{ fontSize: '1.2rem' }}>📋</span>
            <div>
              <div style={{ fontSize: '0.88rem', fontWeight: 800, color: GOLD }}>{['architect','contractor','building_manager'].includes(userRole ?? '') ? 'Full Professional Report' : 'Get Your Full Results'}</div>
              <div style={{ fontSize: '0.65rem', color: profile.text2, marginTop: '0.1rem' }}>One-time purchase · Instant download</div>
            </div>
            <div style={{ marginLeft: 'auto', textAlign:'right' }}>
              <div style={{ fontSize: '0.95rem', fontWeight: 900, color: '#27A96B' }}>FREE</div>
              <div style={{ fontSize: '0.55rem', color: profile.text3, fontFamily:'monospace' }}>BETA</div>
            </div>
          </div>
          <div style={{ fontSize: '0.72rem', color: profile.text2, lineHeight: 1.65, marginBottom: '0.75rem' }}>
            Includes full stair description, detailed code analysis, occupancy classification, applicable bylaw notes, and a pre-inspection summary suitable for a building official.
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.35rem', marginBottom: '0.8rem' }}>
            {['Stair description', 'Code analysis', 'Occupancy type', 'Bylaw notes', 'Inspector summary'].map(tag => (
              <div key={tag} style={{ fontSize: '0.58rem', fontFamily: 'monospace', color: GOLD, background: 'rgba(242,147,55,0.12)', border: '1px solid rgba(242,147,55,0.25)', borderRadius: 10, padding: '0.2rem 0.55rem' }}>{tag}</div>
            ))}
          </div>
          <button onClick={() => { setSheet('plans'); Analytics.pricingViewed() }} style={{ width: '100%', padding: '0.9rem', background: `linear-gradient(135deg, ${GOLD}, #D97706)`, border: 'none', borderRadius: 12, cursor: 'pointer', color: '#000', fontFamily: 'monospace', fontSize: '0.85rem', fontWeight: 800, letterSpacing: '0.1em', boxShadow: `0 4px 20px rgba(242,147,55,0.4)` }}>
            {profile.copy.reportPrice}
          </button>
        </div>
      </div>

      {/* ── STICKY BOTTOM ACTIONS ── */}
      <div className="no-print" style={{ position: 'fixed', bottom: 0, left: '50%', transform: 'translateX(-50%)', width: '100%', maxWidth: 430, padding: '1rem 1.25rem 2.2rem', background: `linear-gradient(to top, ${profile.bg} 70%, transparent)`, display: 'flex', flexDirection: 'column', gap: '0.5rem', zIndex: sheet !== 'hidden' ? 0 : 50, visibility: sheet !== 'hidden' ? 'hidden' : 'visible' }}>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button onClick={() => { setSheet('plans'); Analytics.pricingViewed() }} style={{ flex: 2, padding: '0.9rem', background: `linear-gradient(135deg, ${GOLD}, #D97706)`, border: 'none', borderRadius: 12, cursor: 'pointer', color: '#000', fontSize: '0.8rem', fontFamily: 'monospace', fontWeight: 800, letterSpacing: '0.08em', boxShadow: `0 4px 20px rgba(242,147,55,0.4)` }}>
            📋 {profile.copy.reportPrice}
          </button>
          <button onClick={openArchMap} style={{ flex: 1, padding: '0.9rem', borderRadius: 12, background: profile.bg3, border: `1px solid rgba(147,186,212,0.20)`, cursor: 'pointer', color: profile.text, fontSize: '0.76rem', fontFamily: 'monospace', fontWeight: 700 }}>
            {profile.copy.findInspector}
          </button>
        </div>
        <div style={{ display: 'flex', justifyContent: 'center', gap: '1.5rem' }}>
          {([['↩ Retake', onRetake], ['⟳ Start Over', onStartOver]] as const).map(([label, fn]) => (
            <button key={label} onClick={fn} style={{ background: 'none', border: 'none', color: profile.text3, fontSize: '0.67rem', fontFamily: 'monospace', cursor: 'pointer', letterSpacing: '0.06em' }}>{label}</button>
          ))}
        </div>
      </div>

      {/* ── EMAIL PROMPT MODAL ── */}
      {showEmailPrompt && (
        <>
          <div
            onClick={() => setShowEmailPrompt(false)}
            style={{ position:'fixed', inset:0, background:'rgba(0,0,0,0.75)', zIndex:300 }}
          />
          <div style={{
            position:'fixed', bottom:0, left:'50%', transform:'translateX(-50%)',
            width:'100%', maxWidth:430, zIndex:301,
            background:profile.bg2, borderRadius:'22px 22px 0 0',
            padding:'1.5rem 1.5rem 2.5rem',
            boxShadow:'0 -8px 40px rgba(0,0,0,0.6)',
          }}>
            {/* Handle */}
            <div style={{ width:36, height:4, borderRadius:2, background:'rgba(147,186,212,0.25)', margin:'0 auto 1.25rem' }} />

            {/* Icon + heading */}
            <div style={{ textAlign:'center', marginBottom:'1.25rem' }}>
              <div style={{ fontSize:'2rem', marginBottom:'0.4rem' }}>📧</div>
              <div style={{ fontSize:'1.1rem', fontWeight:900, color:profile.text, marginBottom:'0.3rem', letterSpacing:'-0.01em' }}>
                Where should we send your report?
              </div>
              <div style={{ fontSize:'0.75rem', color:profile.text2, lineHeight:1.6 }}>
                Your full compliance report will be emailed as a PDF instantly after generation.
              </div>
            </div>

            {/* Email input */}
            <input
              id="report-email-input"
              name="email"
              type="email"
              inputMode="email"
              autoComplete="email"
              autoFocus
              placeholder="your@email.com"
              value={emailInput}
              onChange={e => setEmailInput(e.target.value)}
              onKeyDown={e => {
                if (e.key === 'Enter' && emailInput.includes('@')) {
                  setShowEmailPrompt(false)
                  handlePurchaseAndGenerate()
                }
              }}
              style={{
                width:'100%', padding:'0.9rem 1rem',
                background:'rgba(255,255,255,0.06)',
                border:`1.5px solid ${emailInput.includes('@') ? PASS : 'rgba(147,186,212,0.25)'}`,
                borderRadius:14, color:profile.text,
                fontSize:'1rem', fontFamily:'-apple-system,sans-serif',
                outline:'none', marginBottom:'0.85rem',
                transition:'border-color 0.15s',
              }}
            />

            {/* CTA */}
            <button
              onClick={() => {
                if (!emailInput.includes('@')) return
                setShowEmailPrompt(false)
                handlePurchaseAndGenerate()
              }}
              disabled={!emailInput.includes('@')}
              style={{
                width:'100%', padding:'1rem',
                background: emailInput.includes('@')
                  ? 'linear-gradient(135deg,#27A96B,#1A7A50)'
                  : 'rgba(255,255,255,0.06)',
                border:'none', borderRadius:14,
                color: emailInput.includes('@') ? '#fff' : profile.text3,
                fontSize:'0.95rem', fontWeight:800, fontFamily:'monospace',
                letterSpacing:'0.06em', cursor: emailInput.includes('@') ? 'pointer' : 'not-allowed',
                boxShadow: emailInput.includes('@') ? '0 4px 20px rgba(39,169,107,0.4)' : 'none',
                transition:'all 0.15s', marginBottom:'0.75rem',
              }}
            >
              ✓ Send Report to This Email →
            </button>

            <button
              onClick={() => setShowEmailPrompt(false)}
              style={{ width:'100%', background:'none', border:'none', color:profile.text3, fontSize:'0.72rem', fontFamily:'monospace', cursor:'pointer', padding:'0.4rem' }}
            >
              ← Cancel
            </button>

            <div style={{ textAlign:'center', marginTop:'0.75rem', fontSize:'0.6rem', color:profile.text3, lineHeight:1.6 }}>
              Your email is only used to send this report. We never share it.
            </div>
          </div>
        </>
      )}

      {/* ── BOTTOM SHEET ── */}
      {sheet !== 'hidden' && (
        <>
          <div onClick={() => { if (sheet !== 'purchase-report') setSheet('hidden') }} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.72)', zIndex: 90 }} />
          <div style={{ position: 'fixed', bottom: 0, left: '50%', transform: 'translateX(-50%)', width: '100%', maxWidth: 430, zIndex: 100, background: profile.bg3, borderRadius: '22px 22px 0 0', padding: '1.25rem 1.25rem 3rem', display: 'flex', flexDirection: 'column', gap: '0.9rem', boxShadow: '0 -8px 40px rgba(0,0,0,0.7)', maxHeight: '90dvh', overflowY: 'auto' }}>
            <div style={{ width: 36, height: 4, borderRadius: 2, background: 'rgba(147,186,212,0.25)', alignSelf: 'center', marginBottom: '0.1rem', flexShrink: 0 }} />

            {/* ── PLANS SHEET ── */}
            {sheet === 'plans' && <>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.1rem', fontWeight: 800, color: profile.text, marginBottom: '0.25rem' }}>Get Your Report</div>
                <div style={{ fontSize: '0.75rem', color: profile.text2, lineHeight: 1.6 }}>Choose the option that fits your needs.</div>
              </div>

              {/* ── $11.99 REPORT ── */}
              <div style={{ border: `2px solid ${GOLD}`, borderRadius: 16, padding: '1rem 1.1rem', background: 'rgba(242,147,55,0.07)', position: 'relative' }}>
                <div style={{ position: 'absolute', top: -12, left: 14, background: GOLD, borderRadius: 20, padding: '0.18rem 0.75rem', fontSize: '0.58rem', fontFamily: 'monospace', fontWeight: 700, letterSpacing: '0.1em', color: '#000' }}>RECOMMENDED</div>
                <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <div>
                    <div style={{ fontWeight: 800, fontSize: '1.05rem', color: profile.text }}>Full Report</div>
                    <div style={{ fontSize: '0.65rem', color: profile.text2 }}>This inspection only · Instant PDF</div>
                  </div>
                  <div style={{ display:'flex', alignItems:'baseline', gap:'0.5rem' }}>
                    <div style={{ fontWeight: 900, fontSize: '1.5rem', color: GOLD }}>FREE</div>
                    <div style={{ fontSize:'0.75rem', fontFamily:'monospace', color: profile.pass || '#27A96B', fontWeight:700 }}>DURING BETA</div>
                  </div>
                  <div style={{ fontSize:'0.62rem', color: profile.text3, fontFamily:'monospace', marginTop:'0.15rem', textDecoration:'line-through' }}>normally $11.99</div>
                </div>
                {[
                  '📋  Full stair description & dimensions',
                  '⚖️  Detailed compliance analysis per item',
                  '🏛️  Applicable code sections cited',
                  '🏢  Occupancy type classification',
                  '📜  Relevant bylaw & amendment notes',
                  '🔍  Pre-inspection summary for inspector',
                ].map(f => (
                  <div key={f} style={{ fontSize: '0.72rem', color: profile.text2, padding: '0.18rem 0', display: 'flex', gap: '0.45rem' }}>
                    <span style={{ color: GOLD, flexShrink: 0 }}>✓</span> {f}
                  </div>
                ))}
                {/* ── Experiment: print-report ── test = urgent CTA, control = default ── */}
                {isTestVariant ? (
                  <div>
                    <button
                      onClick={() => { Analytics.purchaseInitiated('report'); handlePurchaseAndGenerate() }}
                      style={{ width: '100%', marginTop: '0.85rem', padding: '1.1rem', background: 'linear-gradient(135deg, #27A96B, #1A7A50)', border: '2px solid rgba(39,169,107,0.6)', borderRadius: 14, cursor: 'pointer', color: '#fff', fontFamily: 'monospace', fontSize: '0.95rem', fontWeight: 900, letterSpacing: '0.06em', boxShadow: '0 6px 28px rgba(39,169,107,0.55)' }}>
                      📋 Generate My Free Report →
                    </button>
                    <div style={{ display:'flex', alignItems:'center', justifyContent:'center', gap:'0.4rem', marginTop:'0.45rem' }}>
                      <span style={{ fontSize:'0.65rem', color:'#27A96B', fontWeight:700 }}>✓ FREE during beta</span>
                      <span style={{ fontSize:'0.6rem', color: profile.text3 }}>· Normally $11.99 · Emailed instantly</span>
                    </div>
                  </div>
                ) : (
                  <div>
                    <button
                      onClick={() => { Analytics.purchaseInitiated('report'); handlePurchaseAndGenerate() }}
                      style={{ width: '100%', marginTop: '0.85rem', padding: '0.95rem', background: 'linear-gradient(135deg, #27A96B, #1A7A50)', border: 'none', borderRadius: 12, cursor: 'pointer', color: '#fff', fontFamily: 'monospace', fontSize: '0.88rem', fontWeight: 800, letterSpacing: '0.08em', boxShadow: '0 4px 20px rgba(39,169,107,0.45)' }}>
                      ✓ Get Free Report (Beta) →
                    </button>
                    <div style={{ fontSize:'0.6rem', color: profile.text3, textAlign:'center', marginTop:'0.3rem', fontFamily:'monospace' }}>
                      Free during beta · Normally $11.99
                    </div>
                  </div>
                )}
                <div style={{ fontSize: '0.6rem', color: profile.text3, textAlign: 'center', marginTop: '0.5rem' }}>Secure payment · Instant download · No subscription</div>
              </div>

              {/* ── PRO ── */}
              <div style={{ border: `1.5px solid ${profile.accent}55`, borderRadius: 16, padding: '0.9rem 1.1rem', background: 'rgba(65,124,164,0.05)' }}>
                <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.95rem', color: profile.text }}>Pro</div>
                    <div style={{ fontSize: '0.63rem', color: profile.text2 }}>Homeowners · Contractors · Inspectors</div>
                  </div>
                  <div style={{ color: profile.accent, fontWeight: 800, fontSize: '1.1rem' }}>$38.99<span style={{ fontSize: '0.62rem', color: profile.text3, fontWeight: 400 }}>/mo</span></div>
                </div>
                {[
                  'Unlimited scans & full reports',
                  'AR plane detection — ±2mm accuracy',
                  'All 8 dimensions + full code library',
                  'OBC 2024, NBC, BCBC, IRC + 6 more',
                ].map(f => (
                  <div key={f} style={{ fontSize: '0.7rem', color: profile.text2, padding: '0.15rem 0', display: 'flex', gap: '0.4rem' }}>
                    <span style={{ color: profile.accent, flexShrink: 0 }}>✓</span> {f}
                  </div>
                ))}
                <button onClick={() => { Analytics.purchaseInitiated('pro'); handleProCheckout() }} style={{ width: '100%', marginTop: '0.75rem', padding: '0.85rem', background: profile.accent, border: 'none', borderRadius: 12, cursor: 'pointer', color: '#fff', fontFamily: 'monospace', fontSize: '0.8rem', fontWeight: 700, letterSpacing: '0.08em', boxShadow: `0 3px 14px rgba(65,124,164,0.35)` }}>
                  {proLoading ? 'Redirecting…' : 'Start Pro — $38.99/mo →'}
                </button>
              </div>

              {/* ── ENTERPRISE ── */}
              <div style={{ border: `1px solid rgba(255,255,255,0.1)`, borderRadius: 16, padding: '0.85rem 1.1rem', background: 'rgba(147,186,212,0.04)' }}>
                <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: '0.4rem' }}>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.92rem', color: profile.text }}>Enterprise / Studio</div>
                    <div style={{ fontSize: '0.63rem', color: profile.text2 }}>Architecture firms · Engineering teams</div>
                  </div>
                  <div style={{ color: ORANGE, fontWeight: 700 }}>Custom</div>
                </div>
                {['Team seats & shared reports', 'API access & BIM export', 'Custom code library', 'Dedicated support'].map(f => (
                  <div key={f} style={{ fontSize: '0.68rem', color: profile.text2, padding: '0.12rem 0', display: 'flex', gap: '0.4rem' }}>
                    <span style={{ color: ORANGE, flexShrink: 0 }}>✓</span> {f}
                  </div>
                ))}
                <button onClick={() => { Analytics.purchaseInitiated('enterprise'); window.open('https://calendly.com/staircode/30min', '_blank') }} style={{ width: '100%', marginTop: '0.65rem', padding: '0.8rem', background: 'rgba(242,147,55,0.12)', border: `1px solid ${ORANGE}44`, borderRadius: 12, cursor: 'pointer', color: ORANGE, fontFamily: 'monospace', fontSize: '0.75rem', fontWeight: 700, letterSpacing: '0.08em' }}>
                  Book a Call →
                </button>
              </div>

              <button onClick={() => setSheet('free-confirm')} style={{ background: 'none', border: 'none', color: profile.text3, fontSize: '0.66rem', fontFamily: 'monospace', cursor: 'pointer', letterSpacing: '0.06em', alignSelf: 'center' }}>
                Continue with free pre-analysis only
              </button>
            </>}

            {/* ── GENERATING SHEET ── */}
            {sheet === 'purchase-report' && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1.2rem', padding: '1.5rem 0' }}>
                {generating ? <>
                  <div style={{ width: 48, height: 48, borderRadius: '50%', border: `3px solid rgba(242,147,55,0.2)`, borderTopColor: GOLD, animation: 'spin 0.9s linear infinite' }} />
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '1rem', fontWeight: 700, color: profile.text, marginBottom: '0.4rem' }}>Generating your report…</div>
                    <div style={{ fontSize: '0.75rem', color: profile.text2, lineHeight: 1.6, maxWidth: 280 }}>
                      Claude is analysing your measurements against {codeLabel} and preparing a full compliance report. This takes 15–30 seconds.
                    </div>
                  </div>
                </> : genError ? <>
                  <div style={{ fontSize: '2rem' }}>⚠️</div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontSize: '0.9rem', fontWeight: 700, color: profile.warn, marginBottom: '0.5rem' }}>Report generation failed</div>
                    <div style={{ fontSize: '0.75rem', color: profile.text2, lineHeight: 1.6 }}>{genError}</div>
                  </div>
                  <button onClick={handlePurchaseAndGenerate} style={{ padding: '0.85rem 2rem', background: GOLD, border: 'none', borderRadius: 12, cursor: 'pointer', color: '#000', fontFamily: 'monospace', fontWeight: 700 }}>Try Again</button>
                  <button onClick={() => { setSheet('plans'); Analytics.pricingViewed() }} style={{ background: 'none', border: 'none', color: profile.text3, fontSize: '0.7rem', fontFamily: 'monospace', cursor: 'pointer' }}>← Back</button>
                </> : null}
                <style>{`@keyframes spin { to { transform: rotate(360deg) } }`}</style>
              </div>
            )}

            {/* ── REPORT READY SHEET ── */}
            {sheet === 'report-ready' && reportText && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: '1.3rem', marginBottom: '0.3rem' }}>✅</div>
                  <div style={{ fontSize: '1rem', fontWeight: 800, color: profile.text, marginBottom: '0.2rem' }}>Report Ready</div>
                  <div style={{ fontSize: '0.72rem', color: profile.text2 }}>Generated {new Date().toLocaleTimeString()}</div>
                </div>

                {/* Report preview */}
                <div ref={reportRef} style={{ background: profile.bg2, border: `1px solid ${profile.bg3}`, borderRadius: 14, padding: '1rem', maxHeight: '40dvh', overflowY: 'auto' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif", fontSize: '0.72rem', color: profile.text2, lineHeight: 1.7 }}>
                    {reportText}
                  </pre>
                </div>

                {/* Survey link — tracked by PostHog */}
                {process.env.NEXT_PUBLIC_SURVEY_URL && (
                  <a
                    href={process.env.NEXT_PUBLIC_SURVEY_URL}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={() => Analytics.surveyLinkClicked('in_app_report')}
                    style={{
                      display:'flex', alignItems:'center', justifyContent:'center', gap:'0.5rem',
                      width:'100%', padding:'0.8rem',
                      background:'rgba(65,124,164,0.10)', border:'1.5px solid rgba(65,124,164,0.30)',
                      borderRadius:14, color:'#417CA4',
                      fontFamily:'monospace', fontSize:'0.78rem', fontWeight:700,
                      textDecoration:'none', marginBottom:'0.5rem',
                      letterSpacing:'0.04em',
                    }}
                  >
                    📋 Take our 2-min Beta Survey →
                  </a>
                )}

                <button onClick={printReport} disabled={emailSending} style={{ width: '100%', padding: '1rem', background: `linear-gradient(135deg, ${GOLD}, #D97706)`, border: 'none', borderRadius: 14, cursor: emailSending ? 'wait' : 'pointer', color: '#000', fontFamily: 'monospace', fontSize: '0.88rem', fontWeight: 800, letterSpacing: '0.1em', boxShadow: `0 4px 20px rgba(242,147,55,0.4)` }}>
                  {emailSending ? '📨  Sending to your email…' : emailSent ? '✅  Sent to email · Print copy →' : '🖨  Print / Save as PDF'}
                </button>
                {emailSent && (
                  <div style={{ textAlign:'center', fontSize:'0.68rem', color: profile.text2, marginTop:'-0.2rem' }}>
                    Report sent to {userEmail || 'your email'}
                  </div>
                )}

                <button onClick={() => { Analytics.exportClicked('copy'); navigator.clipboard?.writeText(reportText).catch(() => {}) }} style={{ width: '100%', padding: '0.85rem', background: profile.bg2, border: `1px solid ${profile.bg3}`, borderRadius: 14, cursor: 'pointer', color: profile.text2, fontFamily: 'monospace', fontSize: '0.8rem', fontWeight: 600 }}>
                  📋  Copy to Clipboard
                </button>

                <button onClick={() => setSheet('hidden')} style={{ background: 'none', border: 'none', color: profile.text3, fontSize: '0.68rem', fontFamily: 'monospace', cursor: 'pointer', alignSelf: 'center' }}>
                  ← Back to summary
                </button>
              </div>
            )}

            {/* ── FREE CONFIRM ── */}
            {sheet === 'free-confirm' && <>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1rem', fontWeight: 800, color: profile.text, marginBottom: '0.3rem' }}>Free Pre-Analysis Only</div>
                <div style={{ fontSize: '0.75rem', color: profile.text2, lineHeight: 1.65 }}>The summary above is all you'll get. No occupancy analysis, no code citations, no inspector summary.</div>
              </div>
              <div style={{ background: 'rgba(242,147,55,0.1)', border: `1px solid rgba(242,147,55,0.3)`, borderRadius: 12, padding: '0.75rem 0.9rem', fontSize: '0.68rem', color: profile.text2, lineHeight: 1.65 }}>
                <strong style={{ color: profile.warn }}>⚠ Note:</strong> Accuracy ±9.5–25mm. Must not be used as evidence of building code compliance.
              </div>
              <button onClick={printFree} style={{ width: '100%', padding: '1rem', background: profile.bg2, border: `1px solid ${profile.bg3}`, borderRadius: 12, cursor: 'pointer', color: profile.text2, fontFamily: 'monospace', fontSize: '0.82rem', fontWeight: 700, letterSpacing: '0.08em' }}>
                🖨  Download Free Summary
              </button>
              <button onClick={() => { setSheet('plans'); Analytics.pricingViewed() }} style={{ background: 'none', border: 'none', color: profile.text3, fontSize: '0.65rem', fontFamily: 'monospace', cursor: 'pointer', alignSelf: 'center' }}>
                ← Back to options
              </button>
            </>}
          </div>
        </>
      )}
    </div>
  )
}
